global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: linux
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/*.yml

  - job_name: proxmox
    metrics_path: /pve

    params:
      cluster: ['1']
      node: ['1']

static_configs:
  - targets:
      - <PROXMOX_NODE_01_IP>
    labels:
      module: pve01

  - targets:
      - <PROXMOX_NODE_02_IP>
    labels:
      module: pve02

  - targets:
      - <PROXMOX_NODE_03_IP>
   
 labels:
      module: pve03

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [module]
        target_label: __param_module

      - target_label: __address__
        replacement: proxmox-exporter:9221

      - source_labels: [__param_target]
        target_label: instance

  - job_name: proxmox-exporter
    static_configs:
      - targets:
          - proxmox-exporter:9221
